### ISSUE TITLE
Tests result is written in one test

### ISSUE THREAD

**Issue by VSharovatov** [PeterNgTr/codeceptjs-testrail#1]
Hi, thanks for your plugin. When I run two tests, the result in the testrail is written to one test. I saw that you fixed this problem, but it is repeat. Thanks
![image](https://user-images.githubusercontent.com/15959625/58265817-13f00780-7d89-11e9-84be-f78832e40a38.png)

**Comment by PeterNgTr** [comment]
Can you please expose more information regarding two tests? Does it mean two scenarios in one feature test file?

**Comment by VSharovatov** [comment]
Hello. I checked all the cases.
1. Two scenarios in one feature test file.
 2. One scenario in two features tests files

Result first and second case in testrail is the same.

чт, 23 мая 2019 г. в 20:25, Peter Nguyen Tr <notifications@github.com>:

**Comment by VSharovatov** [comment]
![testrail_result](https://user-images.githubusercontent.com/15959625/58311396-8b697980-7e11-11e9-8e89-53f579086c48.png)
![One scenario in two features tests files](https://user-images.githubusercontent.com/15959625/58311415-93c1b480-7e11-11e9-887d-b4318748bd9f.png)
![Two scenarios in one feature test file](https://user-images.githubusercontent.com/15959625/58311416-93c1b480-7e11-11e9-929a-b695e27d891e.png)

**Comment by PeterNgTr** [comment]
@VSharovatov could you help testing with latest version? I hope this will fix your issue.

**Comment by VSharovatov** [comment]
@PeterNgTr  I has tested latest version and everything worked fine. Thanks.

**Comment by PeterNgTr** [comment]
perfect! Thanks @VSharovatov!
