### ISSUE TITLE
Failure on results attachment

### ISSUE THREAD

**Issue by cat-ninja** [PeterNgTr/codeceptjs-testrail#12]
Hi! I found that at the end of the test there may be an error in results attachment.
If I'm commenting a line of code that you can see in this snippet it works well.
```
	if (helper) {
		testrail.addAttachmentToResult(resultId, attachments[test.id]);
		try {
			log.debug('Remove the screenshot file afterwards');
	//		fs.unlinkSync(global.output_dir + '/' + attachments[test.id]);
			log.debug('File is removed');
		} catch (err) {
			output.error(`Cannot remove file due to ${err}`);
		}
	}
```

That's what I'm seeing without any changes in the code:
![image](https://user-images.githubusercontent.com/17785134/75369064-be2a2c00-58d3-11ea-88c0-ed45d7b5c68c.png)

P.S: I have 2 test cases in the test scenario name so this may be the reason

**Comment by cat-ninja** [comment]
I may be figured out why it's happening. I have 2 test cases in the scenario name, so the attachment comes to the first test case and then gets deleted. Is it possible?

**Comment by PeterNgTr** [comment]
@cat-ninja maybe due to the path separator is different from unix* and windows that causes the issue.

Also I think removing screenshots action would not cause trouble if we don't call it. :)

**Comment by cat-ninja** [comment]
@PeterNgTr yeah, and besides of that test run gets stuck after this error

**Comment by PeterNgTr** [comment]
could you help create a PR after you tested it out? I don't have windows nearby :)

**Comment by PeterNgTr** [comment]
@cat-ninja well, I just removed the step to delete screenshots afterwards. I don't think it's necessary :)

**Comment by cat-ninja** [comment]
@PeterNgTr Nice, I created #13 to make it work independently of a platform

**Comment by PeterNgTr** [comment]
cool, thanks @cat-ninja !

**Comment by cat-ninja** [comment]
@PeterNgTr Looks like the latest version that I can get using npm does not include changes from #13 but I saw you merged it. Can you take a look, please?

**Comment by PeterNgTr** [comment]
did you check if you got the latest version? @cat-ninja

**Comment by PeterNgTr** [comment]
@cat-ninja your PR should be there now 
https://github.com/PeterNgTr/codeceptjs-testrail/commit/402dd5a4c6e2c5e7ccc9c6683d186e6fa765b07f

**Comment by cat-ninja** [comment]
@PeterNgTr  Works now, thanks a lot :)
