### ISSUE TITLE
Creating test run with options like different configurations

### ISSUE THREAD

**Issue by xgene34** [PeterNgTr/codeceptjs-testrail#16]
Hi,

I was wondering if it's possible to create testrun and then add some custom configuration automatically?
Because I have like same testcase that I run for different configuration and when creating testrun I add one test case with different configurations.
something like this:
![image](https://user-images.githubusercontent.com/13034039/76502784-fa699a80-6444-11ea-9d88-f5262c643480.png)

Thanks.

**Comment by PeterNgTr** [comment]
@xgene34 could you expose more regarding the custom configuration? I didn’t get it :)

**Comment by xgene34** [comment]
@PeterNgTr -  So as a matter a fact we need to create Test Plan and add Test Suit to it like:
![image](https://user-images.githubusercontent.com/13034039/76503567-6567a100-6446-11ea-8cdf-13c5220113e1.png)

Then there is "Configuration" button:
![image](https://user-images.githubusercontent.com/13034039/76503677-90ea8b80-6446-11ea-8d99-98f026308ae1.png)

and when clicking on configuration: you can add configuration group and configurations to it:
![image](https://user-images.githubusercontent.com/13034039/76503877-f179c880-6446-11ea-9788-9e94c32cd5f5.png)

which all connect to suite that you imported so you don't need to write 50 Test cases for same thing which includes just different setup of the test or suite.

and then you have the case as in screenshot in first post 
hope this is a bit more clear now.

let me know if you need something else from me.

**Comment by PeterNgTr** [comment]
@xgene34 I just did an exploration of this. Related to test plan creation, I think. But could you explain more the flow you need, I don't use this much.

**Comment by xgene34** [comment]
@PeterNgTr 
So as I sad I have like for one Test Case(in my case one test flow) I have multiple configurations/variatons and I normally don't write 50 same test cases for same thing with minor changes and that's where this comes in play regarding this configurations. But test plan comes in play for this and if you have multiple projects and you can add different suits from different projects inside one plan you can track their execution in single plan otherwise you should create multiple test runs for one release let's say.

**Comment by PeterNgTr** [comment]
@xgene34 so basically the full flow should be following when the execution by codeceptjs finished:

-  first create a test plan
- then add test run to that test plan
- add the desired configuration to test run

The thing is here how many test runs are added here, if I understand correctly, it depends on the how many configurations?

**Comment by xgene34** [comment]
@PeterNgTr  so yes basically as you sad but configurations are mapped to specific case. so it could happen that only one case has like 50 configurations and the rest don't have any configuration.

So my thoughts on this are for case/cases with configurations create separate suite/suites with configuration and for rest without configuration. 
Because testrail automatically assigns all cases in suit to all configs.

**Comment by PeterNgTr** [comment]
@xgene34 I don't think the configuration is bonding to the test case when you create the test case, but rather than bonding the the test runs when you create them in test plan, am I right?

**Comment by xgene34** [comment]
@PeterNgTr -  yes, exactly. But the run should contain only cases that have configuration otherwise all cases in run will be assigned to all configs

**Comment by PeterNgTr** [comment]
@xgene34 well, adding test run to test plan via api calls would give you the possibility to provide selected test cases.

**Comment by xgene34** [comment]
@PeterNgTr  yes but can you add something like this with configs to your plugin so there will be possibility to update testrail with the run

**Comment by PeterNgTr** [comment]
@xgene34 I guess it would be possible. But may take a while. :)

**Comment by xgene34** [comment]
@PeterNgTr  I get it, don't expect it to be right away but would be good if you could plan for it in future releases

**Comment by PeterNgTr** [comment]
@xgene34 First step is done, creating the test plan with test run, test results

![](http://g.recordit.co/W2NzzRddfK.gif)

**Comment by xgene34** [comment]
@PeterNgTr cool.. that was fast.

**Comment by PeterNgTr** [comment]
@xgene34 next, add configurations to test run would be a lot fun.

**Comment by xgene34** [comment]
@PeterNgTr  yes, I can imagine that will be interesting, I saw there is an api call for configs also, hope that helps.

**Comment by PeterNgTr** [comment]
@xgene34 cause in configurations they have groups, configurations that bring so much things to handle when you want to provide an easy way to handle them in plugin config section.

**Comment by xgene34** [comment]
@PeterNgTr  yeah I got that. There are lot of work there probably to make that so configurable as you sad in plugin section

**Comment by PeterNgTr** [comment]
@xgene34 what I could think of when you want to use this plugin to add configurations to your test run is:

- the first run to generate the test plan and the test run with desired configuration. 
- the second run to add the test run with another desired configuration to the same test plan. 

Or another possibility:

- there will be multiple test plans and each has a test run with desired configuration.

**Comment by xgene34** [comment]
@PeterNgTr - I would go for first option because creating multiple test plans is not really  useful from my perspective. But in first option can we have also runs without configuration so let's say possibility to have one test plan with mixture of test runs some with and some without configuration?

**Comment by PeterNgTr** [comment]
@xgene34 that would possible, let's say the following:

- if you provide the `testplan_id` > if you provide `configuration`> the new test run is added to provided testplan with configuration.
- if you don't provide the `testplan_id` > if you provide `configuration`> the new test run is added to new created testplan with configuration.
- if you don't provide the `testplan_id` > if you don't  provide `configuration`> the new test run is added to provided testplan without configuration.

**Comment by xgene34** [comment]
@PeterNgTr - yeah sounds good

**Comment by PeterNgTr** [comment]
@xgene34 how easy for you to get the `configuration_id` or `configuration_name` is easier?

**Comment by xgene34** [comment]
@PeterNgTr configuration_name would be easier I think

**Comment by PeterNgTr** [comment]
@xgene34, it's ready `codeceptjs-testrail@1.6.0`. You can give it a try when you like.

**Comment by xgene34** [comment]
@PeterNgTr thanks, I'll try and let you know soon.

**Comment by xgene34** [comment]
@PeterNgTr  so I tried now and creation of plan and run inside works but test case is not assigned to run and not sure about config how this should work. Is it created when added in config? is it possible to add multiple?

**Comment by PeterNgTr** [comment]
https://github.com/PeterNgTr/codeceptjs-testrail/blob/master/readme.md

the flow is it creates test plan > test run > add config to test run. Right now is one config in a config group.

**Comment by xgene34** [comment]
@PeterNgTr  so saw that already but it's not adding config to test run

**Comment by PeterNgTr** [comment]
@xgene34 could you share your codeceptjs config file? are you providing the proper config name?

**Comment by xgene34** [comment]
@PeterNgTr here is my config:
testrail: {
      require: 'codeceptjs-testrail',
      host: 'xxxxxxxxxxxxxx',
      user: 'xxxxxxxxxxx',
      password: 'xxxxxxxxxx,
      suiteId: 1569,
      projectId: 7,
      runName: 'Automated tests run on '+timestamp('DD/MM/YYYY HH:mm'),
      plan: {
        //existingPlanId: ,
        name: 'Automated tests plan on '+timestamp('DD/MM/YYYY HH:mm'),
        description: '',
      },
      configuration: {
        groupName: 'import Payment order files currency configs',
        configName: 'test1'
      },
      enabled: true
    }

**Comment by PeterNgTr** [comment]
@xgene34 

```
groupName: 'import Payment order files currency configs',
configName: 'test1'
```

are those existing in your testrail?

**Comment by xgene34** [comment]
@PeterNgTr  no but config is created inside the plan if I don't have a plan I can't have config there already

**Comment by PeterNgTr** [comment]
@xgene34 currently it fetches all existing configs in testrail not creating something new there.

**Comment by xgene34** [comment]
@PeterNgTr ok I'll give it a try and let you know

**Comment by xgene34** [comment]
@PeterNgTr works fine man. Just one thing is it possible to specify multiple configurations in config? Because I have like 30 different configurations for one case. Thanks

**Comment by PeterNgTr** [comment]
@xgene34 if config stays in different config group, then I would say it's possible to implement that.

**Comment by xgene34** [comment]
@PeterNgTr and if they are all in same group? because I mean I can create separate groups but normally I would use single group with different configurations in it

**Comment by PeterNgTr** [comment]
@xgene34 http://docs.gurock.com/testrail-api2/reference-plans#add_plan_entry

by api calling, there will be error when you are trying to put the 2 configs in the same group to create testrun.

**Comment by xgene34** [comment]
@PeterNgTr shouldn't this be used for adding configs, because we are adding to same config group multiple configs -> test plan and run stay the same 
http://docs.gurock.com/testrail-api2/reference-configs

**Comment by PeterNgTr** [comment]
> @PeterNgTr shouldn't this be used for adding configs, because we are adding to same config group multiple configs -> test plan and run stay the same
> http://docs.gurock.com/testrail-api2/reference-configs

Those are for adding the configs, config groups. it's not related to assign the configs to testrun. 

Assigning the configs to testrun consumes this http://docs.gurock.com/testrail-api2/reference-plans#add_plan_entry

**Comment by xgene34** [comment]
@PeterNgTr yeah but we can add then multiple configs or one config group that has multiple configs it will get assigned to the run?

**Comment by PeterNgTr** [comment]
@xgene34 on the UI, when you try to assign 2 configs of same group, it will create 2 test runs for you. In this plugin, it create a test run, then find the matched config in a config group and assign it to test run. Hence, there will be error when trying to assign 2 configs in the same group.

**Comment by xgene34** [comment]
@PeterNgTr exactly, but that's the point it will create runs for different configs otherwise no difference to having only one test run

**Comment by PeterNgTr** [comment]
@xgene34 the thing here is are you updating the test results to a test run. And you want to create more test runs with different configs, then how the test results be fetched? :)

**Comment by xgene34** [comment]
@PeterNgTr good point but somehow this won't work as I expected like this because I need to update create multiple configs and multiple runs need to be executed and updated accordingly. 
I suggest some type of saving config runs in buffer and updating properly after whole execution has finished.

**Comment by PeterNgTr** [comment]
@xgene34 that's not an easy thing to determine when your the whole execution of different combinations of config are finished if you have multiple codeceptjs configs.

**Comment by PeterNgTr** [comment]
I closed this for now. :)

**Comment by xgene34** [comment]
@PeterNgTr - Sorry man, I'll come back to this as soon as I can :-)
