### ISSUE TITLE
Question: Can I update old test run or not?

### ISSUE THREAD

**Issue by golfzaptw** [PeterNgTr/codeceptjs-testrail#17]
I would like to update an old test run like a 
<img width="226" alt="Screen Shot 2563-04-01 at 16 16 00" src="https://user-images.githubusercontent.com/21608972/78120411-1bb21b00-7434-11ea-9778-132413a6a202.png">

Because I don't have to create more test folders. Can you support this?

**Comment by PeterNgTr** [comment]
@golfzaptw currently it's just creating new test run. I think it's possible to update the existing test run. I'll check.

**Comment by PeterNgTr** [comment]
@golfzaptw try my latest PR https://github.com/PeterNgTr/codeceptjs-testrail/pull/18, if it's good, I'll merge it.

**Comment by golfzaptw** [comment]
@PeterNgTr it's good, thanks

**Comment by PeterNgTr** [comment]
@golfzaptw did the results update properly for you?

**Comment by golfzaptw** [comment]
@PeterNgTr No, It generates new test run.
I think I set up correctly?
```
suiteId: process.env.SUITE_ID_TESTRAIL,  // Get from test suite like a index.php?/suites/view/4524
projectId: process.env.PROJECT_ID_TESTRAIL, // Get from project in test rail like a index.php?/projects/overview/29
runId: process.env.TEST_RUN_ID_TESTRAIL, // Get from test run inside test plan like a index.php?/runs/view/9739
plan: {
        existingPlanId: process.env.TEST_PLAN_ID_TESTRAIL, // Get from test plan like a index.php?/plans/view/9738
},
```

**Comment by PeterNgTr** [comment]
Did you checkout my PR branch?

**Comment by golfzaptw** [comment]
I copy your file in PR branch and replace it in `node_modules/codeceptjs-testrail/index.js`, that's correct?

**Comment by golfzaptw** [comment]
@PeterNgTr And I saw your code, I think It stop in `if (config.plan)` and not update in `await _updateTestRun(runId, ids);`

**Comment by PeterNgTr** [comment]
> @PeterNgTr No, It generates new test run.
> I think I set up correctly?
> 
> ```
> suiteId: process.env.SUITE_ID_TESTRAIL,  // Get from test suite like a index.php?/suites/view/4524
> projectId: process.env.PROJECT_ID_TESTRAIL, // Get from project in test rail like a index.php?/projects/overview/29
> runId: process.env.TEST_RUN_ID_TESTRAIL, // Get from test run inside test plan like a index.php?/runs/view/9739
> plan: {
>         existingPlanId: process.env.TEST_PLAN_ID_TESTRAIL, // Get from test plan like a index.php?/plans/view/9738
> },
> ```

@golfzaptw yeah, remove the plan option in your config if you want to update the existing test run. Cause if providing the plan option, it creates new test run.

**Comment by golfzaptw** [comment]
@PeterNgTr Yes, For now I have
```
testrail: {
            require: 'codeceptjs-testrail',
            host: 'https://cenergy.testrail.net',
            user: process.env.EMAIL_TESTRAIL,
            password: process.env.PASSWORD_TESTRAIL,
            suiteId: process.env.SUITE_ID_TESTRAIL,
            projectId: process.env.PROJECT_ID_TESTRAIL,
            runId: process.env.TEST_RUN_ID_TESTRAIL,
            enabled: true,
        },
```
And after run get error 403 but result updated

**Comment by PeterNgTr** [comment]
Maybe the 403 error comes from another call. I don’t know yet. But at least it worked for you. 😂

**Comment by golfzaptw** [comment]
Yes, you will merge this PR or you will fix the 403 error? 😁

**Comment by PeterNgTr** [comment]
May you post the full error message? Or if you can fix it. That’s also great!

**Comment by golfzaptw** [comment]
Error message: `Cannnot update run due to Error: Request failed with status code 403`
And an error in this function
```
	async updateRun(runId, data) {
		try {
			const res = await axios({
				method: 'post',
				url: 'update_run/' + runId,
				data,
            });
			output.log(`The run with id: ${runId} is updated`);
			return res.data;
		} catch (error) {
			output.error(`Cannnot update run due to ${error}`);
		}

	}
```
But I think that's function is correct.

**Comment by golfzaptw** [comment]
With document [API Testrail](http://docs.gurock.com/testrail-api2/reference-runs#update_run)

**Comment by PeterNgTr** [comment]
Are you providing the proper credentials? Cause it throws 403.

**Comment by golfzaptw** [comment]
This config required only email and password, right?
```
        testrail: {
            require: 'codeceptjs-testrail',
            host: 'https://cenergy.testrail.net',
            user: process.env.EMAIL_TESTRAIL,
            password: process.env.PASSWORD_TESTRAIL,
            suiteId: process.env.SUITE_ID_TESTRAIL,
            projectId: process.env.PROJECT_ID_TESTRAIL,
            runId: process.env.TEST_RUN_ID_TESTRAIL,
            enabled: true,
        },
```

And I set in file .env
```
# Test rail information
EMAIL_TESTRAIL=
PASSWORD_TESTRAIL=
SUITE_ID_TESTRAIL=
PROJECT_ID_TESTRAIL=
TEST_RUN_ID_TESTRAIL=
```
Is it not enough?

**Comment by golfzaptw** [comment]
I think this is not necessary or not.
`await _updateTestRun(runId, ids);`

Because when I comment it, It's passed in function
```
const allResults = passedTests.concat(failedTests);

testrail.addResultsForCases(runId, { results: allResults }).then(res => {
    output.log(`The run ${runId} is updated with ${JSON.stringify(res)}`);
    console.log(allResults);
    failedTests.forEach(test => {
        testrail.getResultsForCase(runId, test.case_id).then(res => {
            if (helper) {
                testrail.addAttachmentToResult(res[0].id, attachments[test.case_id]);
            }
        });

    });
});
```
Response
```
[
  {
    case_id: '489181',
    elapsed: '1s',
    status_id: 1,
    comment: 'Test case C489181 is PASSED.'
  }
]
```
But I don't know, How this works.

**Comment by PeterNgTr** [comment]
```
  Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
    The run with id: 1 is updated
    The reponse is [{"id":3,"test_id":1,"status_id":1,"created_by":1,"created_on":1589465754,"assignedto_id":null,"comment":"Test case C1 is PASSED.","version":null,"elapsed":"11s","def…
    The run 1 is updated with [{"id":3,"test_id":1,"status_id":1,"created_by":1,"created_on":1589465754,"assignedto_id":null,"comment":"Test case C1 is PASSED.","version":null,"elapsed"…
```
@golfzaptw per my testing, it's working fine. I could see the new results on existing run.

my testrail config in config file:
```
    testrail: {
      require: 'codeceptjs-testrail',
      host: 'testrailhost',
      user: 'email',
      password: 'apikey',
      suiteId: 1,
      projectId: 1,
      runId: 1,
      runName: 'Custom run name',
      enabled: true
    }
```

<img width="896" alt="Screen Shot 2020-05-14 at 4 17 42 PM" src="https://user-images.githubusercontent.com/7845001/81945525-82fbe700-95fe-11ea-9699-90a6188b9967.png">
