### ISSUE TITLE
Add support to add reference to test run.

### ISSUE THREAD

**Issue by TripleC1986** [PeterNgTr/codeceptjs-testrail#19]
Hello, I was wondering if we could add support for reading test run from config and passing when we create a test run. I would be more than happy to create the pr for it. Also, I ran my tests with run-workers --suite command and test runs are being created per suite.

**Comment by PeterNgTr** [comment]
Sure, any PR is more than welcome. 😊

**Comment by TripleC1986** [comment]
@PeterNgTr are you also away that providing the --suites param does not combine the results to one run in testrail ?

**Comment by PeterNgTr** [comment]
@TripleC1986 maybe the lib will be reworked once CodeceptJS run-workers is refactored.
