### ISSUE TITLE
Spelling correction in log output 

### ISSUE THREAD

**Issue by ryaxc** [PeterNgTr/codeceptjs-testrail#20]
I wasn't sure what the policy was for reporting issues and/or opening PRs but I found the following in index.js:
https://github.com/PeterNgTr/codeceptjs-testrail/blob/master/index.js#L147
```output.log(`The reponse is ${JSON.stringify(res.data)}`);```
Should be `The response`

**Comment by PeterNgTr** [comment]
Thanks, I fixed them. :)
