### ISSUE TITLE
Log level is hardcoded and overrides environment configuration

### ISSUE THREAD

**Issue by ryaxc** [PeterNgTr/codeceptjs-testrail#21]
The ```output.level(3)``` on https://github.com/PeterNgTr/codeceptjs-testrail/blob/master/index.js#L8 is causing a problem where it forces suite execution to be `verbose` (or at least `debug`, I'm not sure which is "3").  There are two problems with this:
1) It's not respecting the logging level execution as set in either the `codeceptjs run` command or the configuration
2) It's far too much logging detail for many non-local environments since a lot of the secrets get exposed at this level.

Is there any way this can be overridden in the codecept.conf.js plugins.testrail object or can this file be patched to consume the overall codecept suite's logging level?

**Comment by PeterNgTr** [comment]
@ryaxc well, I think I should separate the plugin logs with codeceptjs logs. So I pushed changes on latest version `1.6.1`. Please test it out and report issues if you encounter anything.

**Comment by ryaxc** [comment]
So far so good. Thanks!
