### ISSUE TITLE
Other Axios calls will break while having codecepjs-testrail plugin enabled

### ISSUE THREAD

**Issue by jedicwb** [PeterNgTr/codeceptjs-testrail#32]
Whenever there is another function in the same Codeceptjs test run also using axios and a test uses such a function while also using this testrail plugin, the other axios call will break.

Still not sure what is happening, but it seems like codecepjs-testrail is starting an axios session beforehand and leaving it open, unabling any other feature that also uses axios to run.

I have several axios functions inside my tests to call API endpoints for health check status and other stuff. Everything will work fine with this plugin ONLY after I disabled such functions.

**Comment by jedicwb** [comment]
After some investigation I finally come to the root cause.
This line here:
https://github.com/PeterNgTr/codeceptjs-testrail/blob/2e38f13367e938f5724276d774f0f45aaab015da/index.js#L51

Because of how Codeceptjs loads plugins, this Global configuration of Axios will override any other Axios call in the same test suite, including default Codeceptjs HTTP calls using [REST](https://codecept.io/helpers/REST/?#configuration), which also uses Axios.

Using axios.defaults. is usually a good practice, but can we NOT do this in this particular plugin?

**Comment by PeterNgTr** [comment]
hey @jedicwb thanks for spending time on figure it out the issue. I released new version (1.7.1). Hope it helps!

**Comment by jedicwb** [comment]
Upgraded and now it's solved. Thank you so much! @PeterNgTr
