### ISSUE TITLE
Add results for cases failing if the wrong label is present in the POST request

### ISSUE THREAD

**Issue by vladbalanescu** [PeterNgTr/codeceptjs-testrail#42]
Background:
---
TR API is soooo “great” that if 1 single label is missing from a run and you’re trying to send the results with this 1 culprit label, TR will not accept ANY of the test run’s results and fail with something like this:
```
17:29:17  tests-runner | Cannot add result for case due to Field :results contains one or more invalid results (case C347875 unknown or not part of the test run)
```
This yielded a difference of 24 test results not being published from Jenkins to TR, just because all of them happened to have been run on the same thread where the wrong label was :scream: (i.e. label in code different than the label in TR). 

Solution:
---
In a potential solution, I'll attempt to filter out these "non-existent" labels from TR and only POST the healthy/existent ones and report back to the user of any of which results didn't manage to publish due to them non-existing in the test run.

**Comment by vladbalanescu** [comment]
@PeterNgTr I'm currently working on a fix for this, and debugging locally on my machine to make sure everything works as I think it should, and I'll have a PR on the fly right away 👍

**Comment by PeterNgTr** [comment]
Many thanks for your efforts @vladbalanescu

**Comment by vladbalanescu** [comment]
My absolute pleasure. I won't mind if you can make me a contributor, to not have to push to my fork everytime and just do PRs here straight away 🙃

**Comment by PeterNgTr** [comment]
just sent you the invite @vladbalanescu ;)
