### ISSUE TITLE
Codeceptjs + testrail configuration problem 

### ISSUE THREAD

**Issue by JakubKasprzyk** [PeterNgTr/codeceptjs-testrail#49]
I've installed the plugin and created the first test run - the API integration worked, but after I create the next test run I've started to have some problems with the config. I'm not sure what I'm doing wrong, could you please take a look and help me? 

In testrail I've created a test plan with ID "R27" and inside it I've created a test run with ID "R28" 
Below is my configuration:

` testrail: {
      require: 'codeceptjs-testrail',
      host: 'URL',
      user: 'Username',
      password: 'Password or API key',
      suiteId: 27,
      projectId: 2,
      runId:28
      enabled: true,
    },`

After I run my tests I'm getting the below error message:
"getCases: ERROR - cannot get results for projectId:2 due to Field :suite_id is not a valid ID.
(node:33114) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined"

Here is a screenshot from a testrail how the test plan looks:
![image](https://user-images.githubusercontent.com/67008060/134645738-d57bab45-e5e1-45bf-9d91-6bcea99b96d4.png)

Thank you for your time!

**Comment by Xotabu4** [comment]
@JakubKasprzyk  I got this issue when i got auth errors, had to replace api token with password. Try to add 
`debugLog: true,` for more details

**Comment by JakubKasprzyk** [comment]
@Xotabu4  I've replaced the API token with a password, and run the tests. Unfortunately, it didn't work :disappointed:  - below is a log from console:

`getConfigs: SUCCESS - the response data is []
updateRun: SUCCESS - the request data is runId:28
updateRun: SUCCESS - the response data is {"id":28,"suite_id":2,"name":"Test Run 9/20/2021","description":null,"milestone_id":null,"assignedto_id":null,"include_all":true,"is_completed":false,"completed_on":null,"config":null,"config_ids":[],"passed_count":0,"blocked_count":0,"untested_count":225,"retest_count":0,"failed_count":0,"custom_status1_count":0,"custom_status2_count":0,"custom_status3_count":0,"custom_status4_count":0,"custom_status5_count":0,"custom_status6_count":0,"custom_status7_count":0,"project_id":2,"plan_id":27,"created_on":1632130783,"updated_on":1632132728,"refs":null,"created_by":5,"url":"https://vazco.testrail.io/index.php?/runs/view/28"}

getCases: ERROR - cannot get results for projectId:2 due to Field :suite_id is not a valid test suite.
(node:42416) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at myDirectory/node_modules/codeceptjs-testrail/index.js:251:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:42416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:42416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
Do you have any other ideas?

**Comment by PeterNgTr** [comment]
@JakubKasprzyk nearly a year, not sure if you still encounter this issue with latest version.
