### ISSUE TITLE
Input to TestRail failures from console

### ISSUE THREAD

**Issue by RuslanAisin** [PeterNgTr/codeceptjs-testrail#5]
Is it possible input failures from console?

![image](https://user-images.githubusercontent.com/49075028/67110058-8bac4c00-f1da-11e9-9280-55f8227b17fb.png)
 to TestRail insted unknow information "This test is failed due to {"9":"{}"}"
![image](https://user-images.githubusercontent.com/49075028/67110137-b26a8280-f1da-11e9-9e71-624120d64a58.png)

**Comment by PeterNgTr** [comment]
@RuslanAisin please check out the latest version, this should be improved.

<img width="781" alt="Screenshot 2019-10-21 at 11 14 37" src="https://user-images.githubusercontent.com/7845001/67192574-1e740300-f3f4-11e9-846e-66681c47dd07.png">

**Comment by RuslanAisin** [comment]
cases added to Testrail as untested status
![image](https://user-images.githubusercontent.com/49075028/67211146-f0f27e00-f422-11e9-96db-92bf97e8f3b2.png)

**Comment by PeterNgTr** [comment]
@RuslanAisin this should be fixed in latest version!

**Comment by RuslanAisin** [comment]
Fixed ok! Thank you for very useful feature!
![image](https://user-images.githubusercontent.com/49075028/67214760-f5219a00-f428-11e9-9f1a-da7987106189.png)
