### ISSUE TITLE
With run-workers 12 a lot of results not reported

### ISSUE THREAD

**Issue by Xotabu4** [PeterNgTr/codeceptjs-testrail#58]
Hi, 

My plugin config is:
```
testrail: {
      require: 'codeceptjs-testrail',
      host: 'https://mytestrail.testrail.io/',
      user: process.env.E2E_TESTRAIL_USER,
      password: process.env.E2E_TESTRAIL_PASSWORD,
      projectId: 1,
      suiteId: 2,
      runId: process.env.E2E_TESTRAIL_RUN_ID,
      debugLog: true,
      testCase: {
        passed: { status_id: 7 },
        failed: { status_id: 8 },
      },
      enabled: process.env.E2E_TESTRAIL_USER !== undefined && process.env.E2E_TESTRAIL_PASSWORD !== undefined,
    },

```
when running `codeceptjs run-workers 12`

I getting results like this in console
  FAIL  | 207 passed, 49 failed, 85 skipped   // 43m

But testrail has very few of results reported.
![image](https://user-images.githubusercontent.com/3033972/139071427-f77376d8-cdcf-4be8-98c4-852e7b514f62.png)

Unfortunately `debugLog: true` does not work for parallel executions, so i am not really sure where in source code issues might be. Maybe you have some ideas?

**Comment by PeterNgTr** [comment]
I guess this is fixed by 1.8.12
