### ISSUE TITLE
test results not submitted when before or beforeSuite hooks fail

### ISSUE THREAD

**Issue by ogiexela** [PeterNgTr/codeceptjs-testrail#66]
"codeceptjs": "3.2.2",
"codeceptjs-testrail": "1.8.10",

When Before and BeforeSuite hooks fail the results are not submitted to Test rail

In the example before only the last test that didn't have the Before/BeforeSuites will be reported to test rail with 100% success even though 2 out of 3 tests failed.

Is there a way to submit results for tests that failed because of the Before/BeforeSuites failures?

```
Feature('Before Suite Tests')

BeforeSuite( async ({ I }) => {
  await I.assertEqual(2+2,5)
})

Scenario('@C382885 Before Suite Test 1', async ({ I }) => {
  await I.assertEqual(2,2)
})
```

```
Feature('Before Test Tests')

Before( async ({ I }) => {
  await I.assertEqual(2+2,5)
})

Scenario('@C382886 Before Test Test 1', async ({ I }) => {
  await I.assertEqual(2,2)
})
```

```
Feature('Just Test Tests')

Scenario('@C382887 Just Test Test 1', async ({ I }) => {
  await I.assertEqual(2,2)
})
```

**Comment by PeterNgTr** [comment]
Hi @ogiexela based on the implementation here. We only push results of test events https://github.com/PeterNgTr/codeceptjs-testrail/blob/master/index.js

Before/After is just like the preparation steps more than the test itself. So not really we push the results based on those events.

**Comment by ogiexela** [comment]
Otherwise we are getting false results of 100% passed tests which doesn't match what codeceptjs reports.

Looking at the code  https://github.com/PeterNgTr/codeceptjs-testrail/blob/master/index.js, it would be possible to capture the skipped tests with the reason using the event.dispatcher and submit these tests as failures. perhaps adding a config option "submitSkippedTestsAsFailures"?

```
event.dispatcher.on(event.test.skipped, (test) => {
		...
	});
```

`test` contains skipInfo
```
opts: {
    skipInfo: {
      message: "Skipped due to failure in 'before' hook",
      isFastSkipped: true
    }
  },
```

**Comment by PeterNgTr** [comment]
hi @ogiexela would you try with this https://github.com/PeterNgTr/codeceptjs-testrail/pull/84 to see if it works for you?
