### ISSUE TITLE
Braking change introduced in a patch version

### ISSUE THREAD

**Issue by IBMRob** [PeterNgTr/codeceptjs-testrail#83]
In https://github.com/PeterNgTr/codeceptjs-testrail/pull/65/files a breaking change was introduced to always close tests plans. When following SemVer rules any breaking change means that it should be a major version bump. Are you able to revert that change in the v1 and then put that into a v2 to follow proper semVer rules?

**Comment by PeterNgTr** [comment]
hi @IBMRob would you expose more why this is a breaking change for you?

**Comment by PeterNgTr** [comment]
@IBMRob you can try the latest version with default back to unclose the test plans. Thanks for your report!
