### ISSUE TITLE
 UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by xgene34** [PeterNgTr/codeceptjs-testrail#9]
Hi,

I tried today to use your plugin you created but it doesn't work. I'm getting following error:
(node:21584) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (D:\Dev\codeceptJS\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Dev\codeceptJS\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Dev\codeceptJS\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:21584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

do you know what could be the issue?

Thanks

**Comment by PeterNgTr** [comment]
@xgene34 what is your config file?

**Comment by xgene34** [comment]
This is inside 
testrail: {
      require: 'codeceptjs-testrail',
      host: 'https://URL',
      user: 'USERNAME',
      password: '1DwsVf09t43JMm3CKfWd-4HHFGrh4OPjAa2Yw5FAx',
      suiteId: 1569,
      projectId: 117058,
      runName: 'Automated tests run ${dd/mm/yyy H:M}',
      enabled: true
    }

**Comment by PeterNgTr** [comment]
@xgene34 nothing is wrong it seemed, could you copy the logs when running with --verbose flag?

**Comment by xgene34** [comment]
@PeterNgTr 
here are the logs:
 npx codeceptjs run --grep "Refund" --verbose
(node:27676) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (D:\Dev\codeceptJS\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Dev\codeceptJS\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Dev\codeceptJS\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:27676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
CodeceptJS v2.4.3
Using test root "D:\Dev\codeceptJS"
Helpers: WebDriver, ChaiWrapper, Mochawesome
Plugins: screenshotOnFail, retryFailedStep, testrail


After execution:

 OK  | 1 passed, 11 skipped   // 20s
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
(node:27676) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (D:\Dev\codeceptJS\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Dev\codeceptJS\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Dev\codeceptJS\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:27676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by PeterNgTr** [comment]
@xgene34 well, I'm into this.

**Comment by xgene34** [comment]
@PeterNgTr  thx. Let me know if you figure something out or u need something

**Comment by PeterNgTr** [comment]
oh, the issue comes from here -> https://github.com/PeterNgTr/codeceptjs-testrail/blob/6ddb0e62af7f1968510e46b5ce1de1fcfafb5a49/index.js#L205

`runId` is undefined on that call, hence, it cannot update testrun and leads to the next error. (cannot update test result on that testrun while testrun is null)

**Comment by xgene34** [comment]
@PeterNgTr but shouldn't run be created by plugin?

**Comment by PeterNgTr** [comment]
@xgene34 it's now fixed with `1.4.0`. Closing this for now.

**Comment by xgene34** [comment]
@PeterNgTr  - I noticed today when having more then 2 tests cases to report I get an error in console:

{ id: '720084', elapsed: '7s' }
{ id: '529330', elapsed: '7s' }
(node:28592) UnhandledPromiseRejectionWarning: Error: Cannot attach file due to Error: read ECONNRESET
    at D:\Dev\PayTestFramework\node_modules\codeceptjs-testrail\index.js:156:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28592) UnhandledPromiseRejectionWarning: Error: Cannot attach file due to Error: Request failed with status code 500
    at D:\Dev\PayTestFramework\node_modules\codeceptjs-testrail\index.js:156:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
npm ERR! Test failed.  See above for more details.

Although error appear all tests are reported in testrail. 

Can you help here?
Thanks

**Comment by PeterNgTr** [comment]
> @PeterNgTr - I noticed today when having more then 2 tests cases to report I get an error in console:
> 
> { id: '720084', elapsed: '7s' }
> { id: '529330', elapsed: '7s' }
> (node:28592) UnhandledPromiseRejectionWarning: Error: Cannot attach file due to Error: read ECONNRESET
> at D:\Dev\PayTestFramework\node_modules\codeceptjs-testrail\index.js:156:10
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:28592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:28592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:28592) UnhandledPromiseRejectionWarning: Error: Cannot attach file due to Error: Request failed with status code 500
> at D:\Dev\PayTestFramework\node_modules\codeceptjs-testrail\index.js:156:10
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:28592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> npm ERR! Test failed. See above for more details.
> 
> Although error appear all tests are reported in testrail.
> 
> Can you help here?
> Thanks

Hey @xgene34 are you using the latest version of this lib?

**Comment by xgene34** [comment]
@PeterNgTr ahh it looks like it not :-) I'll try with 1.4.2 I had 1.4.0

**Comment by xgene34** [comment]
@PeterNgTr - so don't get stacktrace now but still I get an error:
Cannot attach file due to Error: read ECONNRESET
Cannot attach file due to Error: Request failed with status code 500
npm ERR! Test failed.  See above for more details.

I also noticed that testrail itself get's unresponsive when sending results to it

**Comment by PeterNgTr** [comment]
@xgene34 could you do me a favor? Run with `--verbose` mode to get more detailed logs.

**Comment by xgene34** [comment]
@PeterNgTr hmm so I updated also codeceptjs now and webdriver and I runned the tests with --verbose mode 
here is the result :
  FAIL  | 6 passed, 2 failed, 4 skipped   // 3m
    Emitted | global.result ([object Object])
    Emitted | global.after ([object Object])
Cannot attach file due to Error: Request failed with status code 500
Cannot attach file due to Error: Request failed with status code 500

**Comment by PeterNgTr** [comment]
@xgene34 are you using self-hosted testrail or cloud testrail? also, please make sure your account has proper permissions for attachments.

http://docs.gurock.com/testrail-userguide/howto-permissions

**Comment by xgene34** [comment]
@PeterNgTr  it's self-hosted. Yeah could be that I don't have permission. Have to check with testrail admin

**Comment by PeterNgTr** [comment]
@xgene34 maybe you should take a look at this. https://discuss.gurock.com/t/cannot-write-to-reports-dir/1617

**Comment by xgene34** [comment]
@PeterNgTr  thanks a lot for the help
